import warnings
from nczarrgenerator import ncs2zarr

warnings.filterwarnings('ignore')

netcdfs = [
    {'path': ['nc/ccm/cdd_month_grid_pen.nc', 'nc/ccm/cdd_month_grid_can.nc'], 'nc_var': 'cdd', 'var': 'cdd_month', 'time_dim': 'time', 'ver_dim': 'lat', 'hor_dim': 'lon', 'nc_projection': 'EPSG:4326', 'calc_min_max': True, 'include_center_calc': True, 'chunk_shape': (12, 43, 69)},
    {'path': ['nc/ccm/cdd_season_grid_pen.nc', 'nc/ccm/cdd_season_grid_can.nc'], 'nc_var': 'cdd', 'var': 'cdd_season', 'time_dim': 'time', 'ver_dim': 'lat', 'hor_dim': 'lon', 'nc_projection': 'EPSG:4326', 'calc_min_max': True, 'include_center_calc': False, 'chunk_shape': (12, 43, 69)},
    {'path': ['nc/ccm/cdd_year_grid_pen.nc', 'nc/ccm/cdd_year_grid_can.nc'], 'nc_var': 'cdd', 'var': 'cdd_year', 'time_dim': 'time', 'ver_dim': 'lat', 'hor_dim': 'lon', 'nc_projection': 'EPSG:4326', 'calc_min_max': True, 'include_center_calc': False, 'chunk_shape': (12, 43, 69)},
    {'path': ['nc/ccm/dr1mm_month_grid_pen.nc', 'nc/ccm/dr1mm_month_grid_can.nc'], 'nc_var': 'dr1mm', 'var': 'dr1mm_month', 'time_dim': 'time', 'ver_dim': 'lat', 'hor_dim': 'lon', 'nc_projection': 'EPSG:4326', 'calc_min_max': True, 'include_center_calc': False, 'chunk_shape': (12, 43, 69)},
    {'path': ['nc/ccm/dr1mm_season_grid_pen.nc', 'nc/ccm/dr1mm_season_grid_can.nc'], 'nc_var': 'dr1mm', 'var': 'dr1mm_season', 'time_dim': 'time', 'ver_dim': 'lat', 'hor_dim': 'lon', 'nc_projection': 'EPSG:4326', 'calc_min_max': True, 'include_center_calc': False, 'chunk_shape': (12, 43, 69)},
    {'path': ['nc/ccm/dr1mm_year_grid_pen.nc', 'nc/ccm/dr1mm_year_grid_can.nc'], 'nc_var': 'dr1mm', 'var': 'dr1mm_year', 'time_dim': 'time', 'ver_dim': 'lat', 'hor_dim': 'lon', 'nc_projection': 'EPSG:4326', 'calc_min_max': True, 'include_center_calc': False, 'chunk_shape': (12, 43, 69)},
    {'path': ['nc/ccm/dtr_month_grid_pen.nc', 'nc/ccm/dtr_month_grid_can.nc'], 'nc_var': 'dtr', 'var': 'dtr_month', 'time_dim': 'time', 'ver_dim': 'lat', 'hor_dim': 'lon', 'nc_projection': 'EPSG:4326', 'calc_min_max': True, 'include_center_calc': False, 'chunk_shape': (12, 43, 69)},
    {'path': ['nc/ccm/dtr_season_grid_pen.nc', 'nc/ccm/dtr_season_grid_can.nc'], 'nc_var': 'dtr', 'var': 'dtr_season', 'time_dim': 'time', 'ver_dim': 'lat', 'hor_dim': 'lon', 'nc_projection': 'EPSG:4326', 'calc_min_max': True, 'include_center_calc': False, 'chunk_shape': (12, 43, 69)},
    {'path': ['nc/ccm/dtr_year_grid_pen.nc', 'nc/ccm/dtr_year_grid_can.nc'], 'nc_var': 'dtr', 'var': 'dtr_year', 'time_dim': 'time', 'ver_dim': 'lat', 'hor_dim': 'lon', 'nc_projection': 'EPSG:4326', 'calc_min_max': True, 'include_center_calc': False, 'chunk_shape': (12, 43, 69)},
    {'path': ['nc/ccm/fd_month_grid_pen.nc', 'nc/ccm/fd_month_grid_can.nc'], 'nc_var': 'fd', 'var': 'fd_month', 'time_dim': 'time', 'ver_dim': 'lat', 'hor_dim': 'lon', 'nc_projection': 'EPSG:4326', 'calc_min_max': True, 'include_center_calc': False, 'chunk_shape': (12, 43, 69)},
    {'path': ['nc/ccm/fd_season_grid_pen.nc', 'nc/ccm/fd_season_grid_can.nc'], 'nc_var': 'fd', 'var': 'fd_season', 'time_dim': 'time', 'ver_dim': 'lat', 'hor_dim': 'lon', 'nc_projection': 'EPSG:4326', 'calc_min_max': True, 'include_center_calc': False, 'chunk_shape': (12, 43, 69)},
    {'path': ['nc/ccm/fd_year_grid_pen.nc', 'nc/ccm/fd_year_grid_can.nc'], 'nc_var': 'fd', 'var': 'fd_year', 'time_dim': 'time', 'ver_dim': 'lat', 'hor_dim': 'lon', 'nc_projection': 'EPSG:4326', 'calc_min_max': True, 'include_center_calc': False, 'chunk_shape': (12, 43, 69)},
    {'path': ['nc/ccm/gtg_month_grid_pen.nc', 'nc/ccm/gtg_month_grid_can.nc'], 'nc_var': 'gtg', 'var': 'gtg_month', 'time_dim': 'time', 'ver_dim': 'lat', 'hor_dim': 'lon', 'nc_projection': 'EPSG:4326', 'calc_min_max': True, 'include_center_calc': False, 'chunk_shape': (12, 43, 69)},
    {'path': ['nc/ccm/gtg_season_grid_pen.nc', 'nc/ccm/gtg_season_grid_can.nc'], 'nc_var': 'gtg', 'var': 'gtg_season', 'time_dim': 'time', 'ver_dim': 'lat', 'hor_dim': 'lon', 'nc_projection': 'EPSG:4326', 'calc_min_max': True, 'include_center_calc': False, 'chunk_shape': (12, 43, 69)},
    {'path': ['nc/ccm/gtg_year_grid_pen.nc', 'nc/ccm/gtg_year_grid_can.nc'], 'nc_var': 'gtg', 'var': 'gtg_year', 'time_dim': 'time', 'ver_dim': 'lat', 'hor_dim': 'lon', 'nc_projection': 'EPSG:4326', 'calc_min_max': True, 'include_center_calc': False, 'chunk_shape': (12, 43, 69)},
    {'path': ['nc/ccm/r20mm_month_grid_pen.nc', 'nc/ccm/r20mm_month_grid_can.nc'], 'nc_var': 'r20mm', 'var': 'r20mm_month', 'time_dim': 'time', 'ver_dim': 'lat', 'hor_dim': 'lon', 'nc_projection': 'EPSG:4326', 'calc_min_max': True, 'include_center_calc': False, 'chunk_shape': (12, 43, 69)},
    {'path': ['nc/ccm/r20mm_season_grid_pen.nc', 'nc/ccm/r20mm_season_grid_can.nc'], 'nc_var': 'r20mm', 'var': 'r20mm_season', 'time_dim': 'time', 'ver_dim': 'lat', 'hor_dim': 'lon', 'nc_projection': 'EPSG:4326', 'calc_min_max': True, 'include_center_calc': False, 'chunk_shape': (12, 43, 69)},
    {'path': ['nc/ccm/r20mm_year_grid_pen.nc', 'nc/ccm/r20mm_year_grid_can.nc'], 'nc_var': 'r20mm', 'var': 'r20mm_year', 'time_dim': 'time', 'ver_dim': 'lat', 'hor_dim': 'lon', 'nc_projection': 'EPSG:4326', 'calc_min_max': True, 'include_center_calc': False, 'chunk_shape': (12, 43, 69)},
    {'path': ['nc/ccm/rti_month_grid_pen.nc', 'nc/ccm/rti_month_grid_can.nc'], 'nc_var': 'rti', 'var': 'rti_month', 'time_dim': 'time', 'ver_dim': 'lat', 'hor_dim': 'lon', 'nc_projection': 'EPSG:4326', 'calc_min_max': True, 'include_center_calc': False, 'chunk_shape': (12, 43, 69)},
    {'path': ['nc/ccm/rti_season_grid_pen.nc', 'nc/ccm/rti_season_grid_can.nc'], 'nc_var': 'rti', 'var': 'rti_season', 'time_dim': 'time', 'ver_dim': 'lat', 'hor_dim': 'lon', 'nc_projection': 'EPSG:4326', 'calc_min_max': True, 'include_center_calc': False, 'chunk_shape': (12, 43, 69)},
    {'path': ['nc/ccm/rti_year_grid_pen.nc', 'nc/ccm/rti_year_grid_can.nc'], 'nc_var': 'rti', 'var': 'rti_year', 'time_dim': 'time', 'ver_dim': 'lat', 'hor_dim': 'lon', 'nc_projection': 'EPSG:4326', 'calc_min_max': True, 'include_center_calc': False, 'chunk_shape': (12, 43, 69)},
    {'path': ['nc/ccm/rx1day_month_grid_pen.nc', 'nc/ccm/rx1day_month_grid_can.nc'], 'nc_var': 'rx1day', 'var': 'rx1day_month', 'time_dim': 'time', 'ver_dim': 'lat', 'hor_dim': 'lon', 'nc_projection': 'EPSG:4326', 'calc_min_max': True, 'include_center_calc': False, 'chunk_shape': (12, 43, 69)},
    {'path': ['nc/ccm/rx1day_season_grid_pen.nc', 'nc/ccm/rx1day_season_grid_can.nc'], 'nc_var': 'rx1day', 'var': 'rx1day_season', 'time_dim': 'time', 'ver_dim': 'lat', 'hor_dim': 'lon', 'nc_projection': 'EPSG:4326', 'calc_min_max': True, 'include_center_calc': False, 'chunk_shape': (12, 43, 69)},
    {'path': ['nc/ccm/rx1day_year_grid_pen.nc', 'nc/ccm/rx1day_year_grid_can.nc'], 'nc_var': 'rx1day', 'var': 'rx1day_year', 'time_dim': 'time', 'ver_dim': 'lat', 'hor_dim': 'lon', 'nc_projection': 'EPSG:4326', 'calc_min_max': True, 'include_center_calc': False, 'chunk_shape': (12, 43, 69)},
    {'path': ['nc/ccm/rx5d_month_grid_pen.nc', 'nc/ccm/rx5d_month_grid_can.nc'], 'nc_var': 'rx5d', 'var': 'rx5d_month', 'time_dim': 'time', 'ver_dim': 'lat', 'hor_dim': 'lon', 'nc_projection': 'EPSG:4326', 'calc_min_max': True, 'include_center_calc': False, 'chunk_shape': (12, 43, 69)},
    {'path': ['nc/ccm/rx5d_season_grid_pen.nc', 'nc/ccm/rx5d_season_grid_can.nc'], 'nc_var': 'rx5d', 'var': 'rx5d_season', 'time_dim': 'time', 'ver_dim': 'lat', 'hor_dim': 'lon', 'nc_projection': 'EPSG:4326', 'calc_min_max': True, 'include_center_calc': False, 'chunk_shape': (12, 43, 69)},
    {'path': ['nc/ccm/rx5d_year_grid_pen.nc', 'nc/ccm/rx5d_year_grid_can.nc'], 'nc_var': 'rx5d', 'var': 'rx5d_year', 'time_dim': 'time', 'ver_dim': 'lat', 'hor_dim': 'lon', 'nc_projection': 'EPSG:4326', 'calc_min_max': True, 'include_center_calc': False, 'chunk_shape': (12, 43, 69)},
    {'path': ['nc/ccm/tnn_month_grid_pen.nc', 'nc/ccm/tnn_month_grid_can.nc'], 'nc_var': 'tnn', 'var': 'tnn_month', 'time_dim': 'time', 'ver_dim': 'lat', 'hor_dim': 'lon', 'nc_projection': 'EPSG:4326', 'calc_min_max': True, 'include_center_calc': False, 'chunk_shape': (12, 43, 69)},
    {'path': ['nc/ccm/tnn_season_grid_pen.nc', 'nc/ccm/tnn_season_grid_can.nc'], 'nc_var': 'tnn', 'var': 'tnn_season', 'time_dim': 'time', 'ver_dim': 'lat', 'hor_dim': 'lon', 'nc_projection': 'EPSG:4326', 'calc_min_max': True, 'include_center_calc': False, 'chunk_shape': (12, 43, 69)},
    {'path': ['nc/ccm/tnn_year_grid_pen.nc', 'nc/ccm/tnn_year_grid_can.nc'], 'nc_var': 'tnn', 'var': 'tnn_year', 'time_dim': 'time', 'ver_dim': 'lat', 'hor_dim': 'lon', 'nc_projection': 'EPSG:4326', 'calc_min_max': True, 'include_center_calc': False, 'chunk_shape': (12, 43, 69)},
    {'path': ['nc/ccm/tr_month_grid_pen.nc', 'nc/ccm/tr_month_grid_can.nc'], 'nc_var': 'tr', 'var': 'tr_month', 'time_dim': 'time', 'ver_dim': 'lat', 'hor_dim': 'lon', 'nc_projection': 'EPSG:4326', 'calc_min_max': True, 'include_center_calc': False, 'chunk_shape': (12, 43, 69)},
    {'path': ['nc/ccm/tr_season_grid_pen.nc', 'nc/ccm/tr_season_grid_can.nc'], 'nc_var': 'tr', 'var': 'tr_season', 'time_dim': 'time', 'ver_dim': 'lat', 'hor_dim': 'lon', 'nc_projection': 'EPSG:4326', 'calc_min_max': True, 'include_center_calc': False, 'chunk_shape': (12, 43, 69)},
    {'path': ['nc/ccm/tr_year_grid_pen.nc', 'nc/ccm/tr_year_grid_can.nc'], 'nc_var': 'tr', 'var': 'tr_year', 'time_dim': 'time', 'ver_dim': 'lat', 'hor_dim': 'lon', 'nc_projection': 'EPSG:4326', 'calc_min_max': True, 'include_center_calc': False, 'chunk_shape': (12, 43, 69)},
    {'path': ['nc/ccm/txx_month_grid_pen.nc', 'nc/ccm/txx_month_grid_can.nc'], 'nc_var': 'txx', 'var': 'txx_month', 'time_dim': 'time', 'ver_dim': 'lat', 'hor_dim': 'lon', 'nc_projection': 'EPSG:4326', 'calc_min_max': True, 'include_center_calc': False, 'chunk_shape': (12, 43, 69)},
    {'path': ['nc/ccm/txx_season_grid_pen.nc', 'nc/ccm/txx_season_grid_can.nc'], 'nc_var': 'txx', 'var': 'txx_season', 'time_dim': 'time', 'ver_dim': 'lat', 'hor_dim': 'lon', 'nc_projection': 'EPSG:4326', 'calc_min_max': True, 'include_center_calc': False, 'chunk_shape': (12, 43, 69)},
    {'path': ['nc/ccm/txx_year_grid_pen.nc', 'nc/ccm/txx_year_grid_can.nc'], 'nc_var': 'txx', 'var': 'txx_year', 'time_dim': 'time', 'ver_dim': 'lat', 'hor_dim': 'lon', 'nc_projection': 'EPSG:4326', 'calc_min_max': True, 'include_center_calc': False, 'chunk_shape': (12, 43, 69)},
]
zarr_path = 'nc/ccm.zarr'
ncs2zarr(netcdfs, zarr_path, beginning=True)

# 7,12m con max/min; nczarrgenerator